X = Y = 200

MAX_ANIMALS_PER_HELPER = 4
MAX_SIGHT_KM = 5
MAX_DISTANCE_KM = 1
MAX_FLOCK_SIZE = 4
ANIMAL_MOVE_PROBABILITY = 0.5

# MIN_T = 2016
MIN_T = 16
MAX_T = MIN_T * 2
START_RAIN = MIN_T / 2

ONE_BYTE = 1 << 8

# UI
GRID_COLOR = (100, 100, 100)
BG_COLOR = (240, 240, 240)
ARK_COLOR = (200, 150, 170)

SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 900
LANDSCAPE_WIDTH = LANDSCAPE_HEIGHT = 800


MARGIN_X = 40
MARGIN_Y = (SCREEN_HEIGHT  - LANDSCAPE_HEIGHT) / 2

LANDSCAPE_NORTH_PX = MARGIN_Y
LANDSCAPE_SOUTH_PX = SCREEN_HEIGHT - MARGIN_Y
LANDSCAPE_WEST_PX = MARGIN_X
LANDSCAPE_EAST_PX = MARGIN_X + LANDSCAPE_WIDTH

NUM_GRID_LINES = 20

ARK_RADIUS = 5
